name: Rust

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always
  # RUSTFLAGS: -D warnings
  # RUSTDOCFLAGS: -D warnings

jobs:
  rust-check:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          # some deps used by eframe, if that is part of the project
          packages: libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev # libgtk-3-dev is used by rfd
          version: 1.0
          execute_install_scripts: true

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check all features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --all-targets

      - name: Check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

      - name: Check no default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --lib --all-targets

      - name: Test doc-tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features

      - name: cargo doc --lib
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --lib --no-deps --all-features

      - name: cargo doc --document-private-items
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --document-private-items --no-deps --all-features

      - name: Build tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-run

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features

  # ---------------------------------------------------------------------------

  check_wasm:
    name: Check wasm32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: wasm32-unknown-unknown
          components: clippy

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Check wasm32
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target wasm32-unknown-unknown --lib

      - name: Clippy wasm32
        run: cargo clippy --target wasm32-unknown-unknown --lib
